Mithil467/mitype

backspace_test.py, mitype/keycheck.py
Fixed the issue of Backspace key not being recognised on macOS.
=> Added the backspace key check for macOS

mitype/calculations.py
Add a check when index is out of range.
=> Fix crash upon typing more characters than text length bug

mitype/app.py
Adds a method (reset_app). Pressing ESC will exit as usual. This fixes #20
=> Press ESC key to reset test

mitype/app.py, mitype/commandline.py
=> Add current text ID on the top left corner

setup.py, tox.ini
=> Use io.open to read file and update envlist for tox #14

mitype/app.py
issue https://github.com/Mithil467/mitype/issues/28
=> Hide cursor when showing result

README.md, setup.py
This PR fixes #45 
Tested with python version - 3.8.5
On operating system - Windows
=> Add OS specific requirements in setup.py

mitype/app.py
This fixes the bug described in #26. The cursor should be placed at the beginning of the text when the application is started.
=> Fix cursor position

mitype/app.py
=> Display stats during replay

mitype/app.py, mitype/keycheck.py
This PR fixes #43 
Tested with python version - 3.7.3
On operating system - Windows 10
=> Add exit with ctrl+c

mitype/app.py, mitype/calculations.py, mitype/history.py
- Add code that calculate accuracy and print it on screen.
- it was necessary to change some small parts of the original, for example: parameter lines_count, so that it was possible to print the new message in the correct layout.
This PR fixes #16
Tested with python version - 3.6.9
On operating system - Linux
=> Add accuracy stat

mitype/app.py, mitype/keycheck.py
This PR fixes #18 
Tested with python version - 3.6.9 
On operating system - Ubuntu 18.04
=> Add feature to switch text snippets stored in database

mitype/app.py, mitype/keycheck.py
This PR fixes #72 
Tested with python version - Python 3.8.5
On operating system - Windows 10
=> Share result on Twitter

mitype/app.py
=> Update original_text_formatted with latest value

mitype/app.py, mitype/calculations.py, mitype/history.py, mitype/keycheck.py
This PR fixes #87 
Tested with python version - 
On operating system -
=> Remove any version checks and code supporting Python 2

mitype/commandline.py, mitype/history.py
This PR fixes #92
Tested with python version - 3.9.6
On operating system - Arch Linux
* both history.py and commandline.py changed
* ~~added header 'ACCURACY' for the last column in the output of `mitype -H`~~
=> Use with statements to open files

mitype/history.py
Tested with python version - 3.9.6
On operating system - Arch Linux
=> add the header ACCURACY to the output of mitype -H

mitype/app.py, mitype/calculations.py, mitype/commandline.py, mitype/database.py, mitype/history.py, mitype/signals.py, mitype/timer.py
Here is a list of things to be worked on in this PR -
=> Refactor code to make it better

mitype/app.py, tests/test_typing.py
This PR fixes #127
Tested with python version - 3.10
=> Count mistyped spaces while calculating accuracy

mitype/app.py
This PR fixes #104 
Tested with python version - 3.10.7
On operating system - Arch Linux
=> Make replay timings accurate

mitype/commandline.py
This PR fixes #151
Tested with python version - 3.8.10
On operating system - Ubuntu 20.04
=> Correctly handle difficulty level of 0

.github/workflows/ci.yml, .github/workflows/update_docs.yml, BUILD.md
This PR fixes #159
Tested with python version - 3.9
=> Use sphinx-build command to update docs

.github/workflows/auto_author_assign.yml, .github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, .github/workflows/update_docs.yml
=> Update actions to latest versions
